<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'examples\\statemachines\\door\\abstractdoorstate' => '/statemachines/Door/AbstractDoorState.php',
                'examples\\statemachines\\door\\closeddoorstate' => '/statemachines/Door/ClosedDoorState.php',
                'examples\\statemachines\\door\\door' => '/statemachines/Door/Door.php',
                'examples\\statemachines\\door\\doorstate' => '/statemachines/Door/DoorState.php',
                'examples\\statemachines\\door\\illegalstatetransitionexception' => '/statemachines/Door/IllegalStateTransitionException.php',
                'examples\\statemachines\\door\\lockeddoorstate' => '/statemachines/Door/LockedDoorState.php',
                'examples\\statemachines\\door\\opendoorstate' => '/statemachines/Door/OpenDoorState.php',
                'examples\\statemachines\\door\\test\\closeddoortest' => '/statemachines/Door/test/ClosedDoorStateTest.php',
                'examples\\statemachines\\door\\test\\lockeddoortest' => '/statemachines/Door/test/LockedDoorStateTest.php',
                'examples\\statemachines\\door\\test\\opendoortest' => '/statemachines/Door/test/OpenDoorStateTest.php',
                'examples\\statemachines\\pwrcall\\abstractpwrcallstate' => '/statemachines/PwrCall/AbstractPwrCallState.php',
                'examples\\statemachines\\pwrcall\\agentcallhangupstate' => '/statemachines/PwrCall/AgentCallHangupState.php',
                'examples\\statemachines\\pwrcall\\custcallhangupstate' => '/statemachines/PwrCall/CustCallHangupState.php',
                'examples\\statemachines\\pwrcall\\endstate' => '/statemachines/PwrCall/EndState.php',
                'examples\\statemachines\\pwrcall\\illegalstatetransitionexception' => '/statemachines/PwrCall/IllegalStateTransitionException.php',
                'examples\\statemachines\\pwrcall\\incallstate' => '/statemachines/PwrCall/InCallState.php',
                'examples\\statemachines\\pwrcall\\nextcallstate' => '/statemachines/PwrCall/NextCallState.php',
                'examples\\statemachines\\pwrcall\\pwrcall' => '/statemachines/PwrCall/PwrCall.php',
                'examples\\statemachines\\pwrcall\\pwrcallstate' => '/statemachines/PwrCall/PwrCallState.php',
                'examples\\statemachines\\pwrcall\\startupstate' => '/statemachines/PwrCall/StartUpState.php',
                'examples\\statemachines\\pwrcall\\technicalproblemstate' => '/statemachines/PwrCall/TechnicalProblemState.php',
                'examples\\statemachines\\pwrcall\\test\\agentcallhanguptest' => '/statemachines/PwrCall/test/AgentCallHangupStateTest.php',
                'examples\\statemachines\\pwrcall\\test\\custcallhanguptest' => '/statemachines/PwrCall/test/CustCallHangupStateTest.php',
                'examples\\statemachines\\pwrcall\\test\\endtest' => '/statemachines/PwrCall/test/EndStateTest.php',
                'examples\\statemachines\\pwrcall\\test\\incalltest' => '/statemachines/PwrCall/test/InCallStateTest.php',
                'examples\\statemachines\\pwrcall\\test\\nextcalltest' => '/statemachines/PwrCall/test/NextCallStateTest.php',
                'examples\\statemachines\\pwrcall\\test\\startuptest' => '/statemachines/PwrCall/test/StartUpStateTest.php',
                'examples\\statemachines\\pwrcall\\test\\technicalproblemtest' => '/statemachines/PwrCall/test/TechnicalProblemStateTest.php',
                'examples\\statemachines\\pwrcall\\test\\userparkedtest' => '/statemachines/PwrCall/test/UserParkedStateTest.php',
                'examples\\statemachines\\pwrcall\\test\\userparkfailtest' => '/statemachines/PwrCall/test/UserParkFailStateTest.php',
                'examples\\statemachines\\pwrcall\\test\\userregfailtest' => '/statemachines/PwrCall/test/UserRegFailStateTest.php',
                'examples\\statemachines\\pwrcall\\test\\waitforuserparkedtest' => '/statemachines/PwrCall/test/WaitForUserParkedStateTest.php',
                'examples\\statemachines\\pwrcall\\test\\waitforuserregtest' => '/statemachines/PwrCall/test/WaitForUserRegStateTest.php',
                'examples\\statemachines\\pwrcall\\test\\wpcompletetest' => '/statemachines/PwrCall/test/WPCompleteStateTest.php',
                'examples\\statemachines\\pwrcall\\userparkedstate' => '/statemachines/PwrCall/UserParkedState.php',
                'examples\\statemachines\\pwrcall\\userparkfailstate' => '/statemachines/PwrCall/UserParkFailState.php',
                'examples\\statemachines\\pwrcall\\userregfailstate' => '/statemachines/PwrCall/UserRegFailState.php',
                'examples\\statemachines\\pwrcall\\waitforuserparkedstate' => '/statemachines/PwrCall/WaitForUserParkedState.php',
                'examples\\statemachines\\pwrcall\\waitforuserregstate' => '/statemachines/PwrCall/WaitForUserRegState.php',
                'examples\\statemachines\\pwrcall\\wpcompletestate' => '/statemachines/PwrCall/WPCompleteState.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
